VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "GLService"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit
'Model: GL Service
'Description: All GL related procedure, such as AddLineItem()

Public Sub AddLineItem()
    ' Call mGLEntity to add column and specific operation
    ' then mGLEntity will call cAccess to operate SQL query.
End Sub
